CREATE SCHEMA NOVA_VISAO;

USE NOVA_VISAO;

CREATE TABLE CLIENTE 
( 
 ID INT unsigned NOT NULL,  
 NOME VARCHAR(100),  
 EMAIL VARCHAR(100),  
 NUM_TELEFONE VARCHAR(100),
 PRIMARY KEY (ID)
); 

CREATE TABLE IMAGEM 
( 
 ID INT unsigned NOT NULL,  
 IMAGEM BLOB,  
 ID_CLIENTE INT unsigned NOT NULL,
 PRIMARY KEY(ID)
); 

ALTER TABLE IMAGEM ADD FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (ID);